fix action

diff --git a/.github/workflows/test_and_format.yml b/.github/workflows/test_and_format.yml
--- a/.github/workflows/test_and_format.yml
+++ b/.github/workflows/test_and_format.yml
@@ -24,7 +24,9 @@ jobs:
         run: flutter test
 
       - name: Format code
-        run: flutter format . --line-length 200
+        run: |
+          dart format . --line-length 200 --output=none $(find . -name "*.dart" ! -name "*.g.dart")
 
-      - name: Check formatting
-        run: flutter format --set-exit-if-changed . --line-length 200 --exclude "example/pubspec.lock"
+      - name: Check for changes
+        run: |
+          git diff --exit-code -- . ':!example/pubspec.lock' || (echo "::error::Code formatting issues found. Run 'dart format --line-length 200 lib/ test/ example/' to fix." && exit 1)
